name: Check EditorConfig

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# ... 其他现有工作流配置 ...

# 添加或替换为以下步骤
- name: Checkout code
  uses: actions/checkout@v3

- name: Install dependencies
  uses: taiki-e/install-action@v1

# ... 其他现有工作流配置 ...


jobs:
  editorconfig-check:
    name: Run EditorConfig Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker -config .ecrc.json
